### ISSUE TITLE
I want to add custom keybindings for preview window to scoll

### ISSUE THREAD

**Issue by prabhu7x** [tomrijndorp/vscode-finditfaster#29]
_First of all big thanks for this wonderful plugin and I like fzf_. I  want to add custom keybindings to scroll up and down, page half up and bottom vice-versa. I set it up for my fzf terminal but i have no idea how to add those  lines to this plugin in vscode. i could't see any related options in vscode **keyboard shortcuts**.  The default `shift + up/down arrow` is not so comfortable for me because I need to give  extra key strokes in my keyboard. 
                                                              Can you help me of this.
_** file up/down with ctrl+ j/k are working fine **_
### info 

- os : Arch Linux

**Comment by tomrijndorp** [comment]
Hi @prabhu7x, I'm not sure whether fzf supports changing those key bindings. If it does (which I'm not super sure of given [this ticket](https://github.com/junegunn/fzf/issues/546)), you'd likely have to do the following because VS Code doesn't know much about what happens within its built in terminal:
1. ensure that there is no key binding inside VS Code (e.g. `shift + up/down arrow`) when the terminal has focus, and
2. use environment variables to configure fzf key bindings. That is, if you for instance launch VS code from a terminal, ensure that that session has the environment configured the way you want.

Good luck :)
