### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by tomrijndorp** [tomrijndorp/vscode-finditfaster#4]
Also see #2. I think there are two options:

1. Invoke the bash scripts from Windows. I'm not sure how / whether this can be done. Will require WSL to be installed. Not sure if there are further issues with access permissions etc. Will require some investigation.
2. Create Windows versions of `find_files.sh` and `find_within_files.sh` (the scripts in the extension that invoke `fzf`). This may be the nicest solution as it's a native implementation, but requires Windows shell scripting, which I'm not familiar at all.

If you're a Windows user, please vote on this ticket using 🚀  for the first solution, 🎉  for the second, or 😕  for don't know / don't care as long as you do something. Votes will compel me to take action (and learn windows batch file scripting).

If you're interested in implementing solution 2 and supporting it, please shoot me a message! The extension is built in such a way that implementing this solution requires writing two scripts that invoke the terminal commands, and there are reference implementations in bash shell script.

**Comment by marblewraith** [comment]
Not a user of this, but i thought i'd provide a bit of rambling which may help.

1. Ripgrep was internalized into VScode some time ago [see package.json](https://github.com/microsoft/vscode/blob/8d584a55949e1501003e436a91c767359b751bd1/package.json#L66).

2. FZF is tricker. The simplest install is the binaries via [chocolatey or scoop](https://github.com/junegunn/fzf#windows). But IMO before you added win support here, fzf should be added to winget since that ships by default win11, related issues here:

- https://github.com/microsoft/winget-pkgs/issues/906
- https://github.com/junegunn/fzf/issues/2661

**Comment by ihdavids** [comment]
https://github.com/tomrijndorp/vscode-finditfaster/pull/18
I just downloaded the windows versions of bat, fzf and ripgrep. The extension scripts are all powershell scripts.

**Comment by tomrijndorp** [comment]
Native Windows support is implemented as of version `0.0.20` now :)
