### ISSUE TITLE
Is this possible to search in files that are open in the current windows but not inside the working directory?

### ISSUE THREAD

**Issue by Ethnical** [tomrijndorp/vscode-finditfaster#45]
Hi! 
Super works, I would like to know if it is possible to be capable of searching the files present in the current Visual Studio windows (even if the files are not in the current directory explorer)
for example here: 
![CleanShot 2023-09-10 at 22 38 04](https://github.com/tomrijndorp/vscode-finditfaster/assets/23560242/8cf0fb16-bfef-4fca-86a4-10faa49fb257)
However, while running the **search within file** this is looking for too many files that is really slow. 
My option for now: 
![CleanShot 2023-09-10 at 22 47 36](https://github.com/tomrijndorp/vscode-finditfaster/assets/23560242/9c48c37a-8004-4579-8995-bbb660d07b66)

**Comment by tomrijndorp** [comment]
Thanks for the suggestion! It looks like it might be possible to do so by keeping track of open files using `onDidOpenTextDocument` and `onDidCloseTextDocument`, and a couple other related events. It seems like a useful feature, though would require a good bit of work to implement correctly in all cases. I'll look into the feasibility of this.

As for searching within files being slow, you could try using `search within files (with type filter)`. Generally, the search tends to be slow only because `rg` ends up running through a bunch of files that shouldn't be indexed in the first place.

**Comment by Ethnical** [comment]
Super thanks for trying to improve this feature!
And will have a look on the filter side thx!
