### ISSUE TITLE
Can't download the extension because it's incompatible with the current version of VS Code. 

### ISSUE THREAD

**Issue by tyconway** [tomrijndorp/vscode-finditfaster#5]
![image](https://user-images.githubusercontent.com/38512092/124147458-526e4b00-da54-11eb-9137-94c83da50b48.png)

**Comment by tomrijndorp** [comment]
Hi tyconway, thanks for bringing this to my attention!

I just pushed a new release (`0.0.13`) that lowers the minimum required version of VS Code to 1.48. It seems like VS Code by default sets whatever version the developer is on as minimum supported version. I tested it myself on 1.48 (July 2020), because a year of backwards support should be sufficient. Please let me know if you can now install.

You still might want to upgrade VS Code though; your version is from November, and a number of fixes have gone into VS Code since. As far as this extension is concerned, I noticed that the terminal doesn't receive proper focus after using the `Find It Faster: search within files (with type filter)` command when I was on 1.48.. This issue is not present on the latest VS Code version.

**Comment by tyconway** [comment]
Of course! I totally didn't realize my VS Code was out of date. I clicked the check for updates in the menu to be sure, but maybe it doesn't fetch certain releases on Mac? I don't know. My apologies for making this an issue! I'm excited to see this. I've enjoyed Code's open a file via `cmd + P` but haven't liked how clunky finding text within files is. Having used `fzf` for command line improvements, I'm looking forward to it. Thanks for your work on this project.
